# Generated by Django 4.1.7 on 2023-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applied_jobs',
            fields=[
                ('applied_jobs_ID', models.AutoField(primary_key=True, serialize=False)),
                ('job_ID', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('job_name', models.CharField(max_length=200)),
                ('student_ID', models.IntegerField(null=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_phone', models.IntegerField(null=True)),
                ('student_email', models.EmailField(max_length=254, null=True)),
                ('area_of_interest', models.CharField(max_length=200)),
                ('skills_required', models.CharField(max_length=300)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('job_ID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_location', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('contact_number', models.IntegerField(null=True)),
                ('job_name', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=400)),
                ('skills_required', models.CharField(max_length=300)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
