# Generated by Django 4.1.7 on 2023-05-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_show_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show_jobs',
            old_name='student_email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='show_jobs',
            old_name='area_of_interest',
            new_name='company_location',
        ),
        migrations.RenameField(
            model_name='show_jobs',
            old_name='applied_jobs_ID',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='show_jobs',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='show_jobs',
            name='student_phone',
        ),
        migrations.AddField(
            model_name='show_jobs',
            name='job_description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='show_jobs',
            name='job_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='show_jobs',
            name='skills_required',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
