# Generated by Django 4.1.7 on 2023-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_of_interest',
            field=models.CharField(max_length=500, null='True'),
        ),
    ]
